### ISSUE TITLE
oneshot may end up renaming/unlinking files outside data_directory

### ISSUE THREAD

**Issue by dualbus** [maxburke/oneshot#2]
A request like this:

    $ curl --path-as-is -d '' http://127.0.0.1:8080/claim/../../../../../../../../../../../../etc/hosts -v

Ends doing things like this:

    [pid  8493] rename("data/../../../../../../../../../../../../etc/hosts", "data/../../../../../../../../../../../../etc/hosts.8493") = -1 EACCES (Permission denied)

Perhaps call realpath() to and then check if the resolved path is inside the data_directory?

**Comment by maxburke** [comment]
Good catch!

I haven't tested for this because the service as deployed runs in a chroot. 

Change a938c24 addresses this by validating the claim IDs are valid.

**Comment by maxburke** [comment]
(and 0571dab)

**Comment by dualbus** [comment]
Verified fix in master:

    dualbus@debian:~/local/src/maxburke/oneshot$ ./oneshot
    oneshot[10799]: 127.0.0.1 - [2017-03-11:09:26:01] "POST /claim/../../../../../../../../../../../../etc/hosts HTTP/1.1" 400 116
