### ISSUE TITLE
Parsing of Content-Length header

### ISSUE THREAD

**Issue by dualbus** [maxburke/oneshot#4]
There are a couple of issues with the parsing of Content-Length:

Using `strtoul` means that it'll not only parse positive decimal numerals. The grammar of `strtoul` is a bit more wide, accepting sign (both positive and negative), it will also understand the 0x prefix as hexadecimal, and a leading 0 as octal. A funny thing is that passing in a negative Content-Length will cause it to be converted to a very large positive number (which seems to be ULONG_MAX). I'm also not sure if it should interpret this header for GET's (which it currently does, causing the thread to hang forever waiting for input). http://stackoverflow.com/questions/8540931/what-is-the-correct-content-length-to-set-for-a-get-request

Also, I think this line:

    const char content_length_header[] = "Content-Length:";

Should be:

    const char content_length_header[] = "\r\nContent-Length:";

Instead. Otherwise you can do fun stuff like: `curl -H 'X-Content-Length: -1' -X GET ...`, which will go past the reverse proxy and cause the oneshot child to remain waiting for input until the reverse proxy times out the connection

Finally, should it use some http_strncasestr instead of http_strnstr ? Since `content-length` is also valid.

**Comment by maxburke** [comment]
> I'm also not sure if it should interpret this header for GET's (which it currently does, causing the thread to hang forever waiting for input). 

It is possible for GET requests to include a body, though I believe they're supposed to not have semantic content. I would be tempted to say a GET request with a Content-Length field but no body is malformed?

Good catch on the others though.

**Comment by maxburke** [comment]
Content-length header case sensitivity fix: 6736473
Non-base 10/negative value handling: bf41657

**Comment by maxburke** [comment]
(Extra test case for non-base10 handling: d8dd988)
