### ISSUE TITLE
test.c:73:9: error: variable ‘failed’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]

### ISSUE THREAD

**Issue by dualbus** [maxburke/oneshot#7]
For some reason, when I compile the code with the AFL GCC wrapper, I get this warning (which is treated as error due to -Werror):

    [+] Instrumented 98 locations (64-bit, non-hardened mode, ratio 100%).
    afl-gcc -c -o test.o test.c -Wall -Wextra -pedantic -g -Werror -std=c11 -I/usr/include -I/usr/local/include -I../include -I../src -D_POSIX_C_SOURCE=200809
    afl-cc 2.36b by <lcamtuf@google.com>
    test.c: In function ‘testcase_run’:
    test.c:73:9: error: variable ‘failed’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
         int failed;
             ^~~~~~
    cc1: all warnings being treated as errors

From http://stackoverflow.com/a/7726144, I gather that `int failed` should be `volatile int failed` to indicate the compiler that it shouldn't perform any weird optimizations on it. Adding the `volatile` modifier fixes the issue for me.

**Comment by dualbus** [comment]
PR: https://github.com/maxburke/oneshot/pull/8

**Comment by dualbus** [comment]
Ah, afl-gcc triggers it because it passes down the -O3 flag. If I add it to CFLAGS tests/makefile, I get the error:

    gcc -c -o test.o test.c -Wall -Wextra -pedantic -g -Werror -std=c11 -O3 -I/usr/include -I/usr/local/include -I../include -I../src -D_POSIX_C_SOURCE=200809
    test.c: In function ‘testcase_run’:
    test.c:73:9: error: variable ‘failed’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
         int failed;
             ^~~~~~
    cc1: all warnings being treated as errors

**Comment by maxburke** [comment]
Nice find.

I deliberately do not optimize this program because in the past I have found GCC's optimizer can make dangerous, not always correct, assumptions. Ditto for Clang.

Still good to fix though. I should probably do a build with optimizations on just to see the warnings it pops up. You can build it with "make OPT=[0|1|2|3|s]" as well.
